---
driver:
  name: vagrant
  synced_folders:
   - [".", "/vagrant"]
  
provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list: recipe[fake::default]
    attributes:
